### PR TITLE
End of first Sprint

### PR DESCRIPTION
**Pull request by coens97**
We added nice knowledge transfer documents and minutes of meeting this sprint

### CODE REVIEW

**Comment by coens97** [comment]
740full-asana-mamoru

**Comment by coens97** [comment]
b2b1bff9jw1f8teimd2wmg209q05gnl9

**Review by bilgeryahov — APPROVED** [review]
Sprint #2 good to go! 😄

**Comment by coens97** [comment]
It is merged, very nice
960full-asana-mamoru-2

**Comment by Fontyschriek** [comment]
act professional & delete images.
i've seen enough of Asana M.

**Pull request merged**
